September-nomaster/September/September/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cart/',include('cart.urls',namespace='cart')),
    url(r'^orders/',include('orders.urls',namespace='orders')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^payment/',include('payment.urls',namespace='payment')),
    url(r'^account/',include('account.urls',namespace='account')),
    url(r'^comment/',include('comment.urls',namespace='comment')),
    url(r'^', include('shop.urls', namespace='shop')),
]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

September-nomaster/September/cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    url(r'^add/(?P<product_id>\d+)/$',views.cart_add,name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$',views.cart_remove,name='cart_remove'),
    url(r'^$',views.cart_detail,name='cart_detail'),
    url(r'^checkout/$',views.checkout,name='checkout'),
    url(r'^change/(?P<product_id>\d+)/$',views.cart_change_num,name='cart_change_num'),
]

September-nomaster/September/orders/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
	url(r'^create/$',views.order_create,name='order_create'),
	url(r'^admin/order/(?P<order_id>\d+)/$',views.admin_order_detail,name='admin_order_detail'),
	url(r'^orderlist/$',views.order_list,name='order_list'),
	url(r'^(?P<id>\d+)/$',views.order_detail,name='order_detail'),
	url(r'^verify/(?P<order_id>\d+)/$',views.VerifyOrder,name='verify'),
]

September-nomaster/September/shop/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
	url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

September-nomaster/September/cart/models.py
from django.db import models
from django.contrib.auth.models import User
from shop.models import Product

class Cart(models.Model):
	user=models.ForeignKey(User,related_name='cart')

	def __str__(self):
		return 'Cart {} of user {}'.format(self.id,self.user.id)

	def get_total_price(self):
		return sum(item.get_price() for item in self.items.all())


class CartItem(models.Model):
	cart=models.ForeignKey(Cart,related_name='items')
	item=models.ForeignKey(Product,related_name='carts')
	item_quantity=models.IntegerField(default=1)

	class Meta:
		ordering=('cart',)

	def __str__(self):
		return 'Product {} in cart {}'.format(self.item.id,self.id)

	def get_price(self):
		return self.item.price*self.item_quantity



September-nomaster/September/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES=[(i,str(i)) for i in range(1,21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,
                                      coerce=int)

September-nomaster/September/cart/views.py
from django.shortcuts import render,redirect,get_object_or_404,reverse
from django.views.decorators.http import require_POST
from shop.models import Product
from .models import Cart,CartItem
from .forms import CartAddProductForm
from django.contrib.auth.decorators import login_required

# 用require_POST来只响应POST请求
@require_POST
@login_required(login_url='/account/login')
def cart_add(request,product_id):
	cart=get_object_or_404(Cart,user=request.user)
	product=get_object_or_404(Product,id=product_id)
	form=CartAddProductForm(request.POST)
	if form.is_valid():
		cd=form.cleaned_data
		item=CartItem.objects.filter(cart=cart,item=product)
		if not item:
			CartItem.objects.create(cart=cart,item=product,item_quantity=cd['quantity'])
		else:
			item[0].item_quantity+=cd['quantity']
			item[0].save()
	return redirect('cart:cart_detail')

def cart_change_num(request,product_id):
	form=CartAddProductForm(request.POST)
	if form.is_valid():
		cd=form.cleaned_data
		cart=get_object_or_404(Cart,user=request.user)
		product=get_object_or_404(Product,id=product_id)
		item=get_object_or_404(CartItem,cart=cart,item=product)
		item.item_quantity=cd['quantity']
		item.save()
	return redirect('cart:cart_detail')



def cart_remove(request,product_id):
	cart=get_object_or_404(Cart,user=request.user)
	product=get_object_or_404(Product,id=product_id)
	item=get_object_or_404(CartItem,cart=cart,item=product)
	item.delete()
	return redirect('cart:cart_detail')

# 获取当前的购物车并展现它
@login_required(login_url='/account/login')
def cart_detail(request):
	cart=get_object_or_404(Cart,user=request.user)
	items=CartItem.objects.filter(cart=cart)
	cart_product_form=CartAddProductForm()
	return render(request,'cart/detail.html',{'cart':cart,'items':items,'cart_product_form':cart_product_form})


def checkout(request):
	if 'checkbox' in request.GET:
		itemlist=request.GET.getlist('checkbox')
		if not itemlist:
			redirect(reverse('cart:cart_detail'))
		else:
			if 'quantity' in request.GET and request.GET['quantity']:
				quantity=request.GET['quantity']
				request.session['quantity']=[]
				for q in quantity:
					request.session['quantity'].append(q)

				request.session['items']=[]
				for idd in itemlist:
					request.session['items'].append(idd)
				return redirect(reverse('orders:order_create'))
			else:
				redirect(reverse('cart:cart_detail'))
	return redirect(reverse('cart:cart_detail'))

	

September-nomaster/September/cart/templates/cart/checkout.html
test....

September-nomaster/September/cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
    Your shopping cart
{% endblock %}

{% block content %}

	<div class="containerz" style="padding: 5em 15em 3em 15em;">
		<div style="padding-bottom:2em">	
            <h3 >购物车</h1>
            {% if error %}
                <p style="color: red">Please choose some products.</p>
            {% endif %}
			<!-- <strong>——————————</strong> -->
			<div style="height:20px; weight:20px; border-bottom:2px solid #000000cc;" ></div>
        </div>
        <form method="GET" action="{% url 'cart:checkout' %}">
        {% csrf_token %}
            <table class="table table-hover" >
                <thead>
                    <tr>
                        <th><input type="checkbox" id="checkAll" name="checkAll"></th>
                        <th>图片</th>
                        <th>名称</th>
                        <th>数量</th>
                        <th>移除</th>
                        <th>单价</th>                
                        <th>总价</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in items %}
                    {% with product=item.item %}
                    <tr>
                        <td>
                            <input type="checkbox" name="checkbox" id="checkbox" value="{{item.id}}">
                        </td>
                        <td>
                            <a href="{{ product.get_absolute_url }}">
                                <!-- <img src="{% if product.image %}{{product.image.url}}{% else %}{% static 'img/no_image.png' %}{% endif %}"> -->
                                <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" class="img-responsive img-thumbnail">
                            </a>
                        </td>
                        <td>{{product.name}}</td>
                        <td>
                            Quantity:{{item.item_quantity}}
                            <div><br></div>
                            <div>
                                <input type="text" name="quantity" class="quantity-field" value="{{item.item_quantity}}">
                                <input type="button" class="quantity-verify" value="更改">
                            </div>
                        </td>
                        <td><a href="{% url 'cart:cart_remove' product.id %}">Remove</a></td>
                        <td class="num unit-price">${{product.price}}</td>
                        <td class="num unit-total-price">${{item.get_price}}</td>
                    </tr>
                    {% endwith %}
                {% endfor %}
                <tr class="total">
                    <td></td>
                    <td><strong>总计</strong></td>
                    <td colspan="4"></td>
                    <td class="num">${{ cart.get_total_price }}</td>
                </tr>
                </tbody>
            </table>
            <p class="text-right">
                <input type="submit" value="Checkout">
                <a href="{% url "shop:product_list" %}" class="btn btn-link" style="color:#000000a4">继续购物</a>
                <!-- <a href="{% url "orders:order_create" %}" class="btn btn-warning" style="color:#000000cc"><strong>结算</strong></a> -->
            </p>
        </form>	
	</div>
    
    <script type="text/javascript">
        $(function(){
            function initTableCheckbox(){
                var $thr=$('table thead tr');
                var $tbr=$('table tbody tr');
                var $checkAllTh=$('<th><input type="checkbox" id="checkAll" name="checkAll"></th>');
                var $checkAll=$thr.find('input');
    
                $checkAll.click(function(event){
                    //所有项的“是否选中”状态设置为“checkAll”的“是否选中”状态
                    $tbr.find('input').prop('checked',$(this).prop('checked'));
                    //阻止向上冒泡，防止再次促发点击操作   这里还需要再看一下
                    event.stopPropagation();
                });
                //点击全选框所在单元格时也触发全选框的点击操作
                $checkAllTh.click(function(){
                    $(this).find('input').click();
    
                });
    
                $tbr.find('input').click(function(event){
                    $checkAll.prop('checked',$tbr.find('input:checked').length==$tbr.length?true:false);
                    event.stopPropagation();
                });
    
            }
            initTableCheckbox();
    
        });
    </script>    
{% endblock %}	